import React, { useEffect, useState } from 'react'
const masterData = [
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "AJ201",
        "CurriculumName": "Ngữ pháp tiếng Nhật 1",
        "CurriculumNamePrint": "Ngữ pháp tiếng Nhật 1",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "6.30",
        "DiemTK_4": "2.52",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "AJ214",
        "CurriculumName": "Văn hóa Nhật Bản 1",
        "CurriculumNamePrint": "Văn hóa Nhật Bản 1",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "7.50",
        "DiemTK_4": "3.00",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "AJ304",
        "CurriculumName": "Ngữ pháp tiếng Nhật 2",
        "CurriculumNamePrint": "Ngữ pháp tiếng Nhật 2",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "6.30",
        "DiemTK_4": "2.52",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "AJ311",
        "CurriculumName": "Đất nước học Nhật Bản",
        "CurriculumNamePrint": "Đất nước học Nhật Bản",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "8.10",
        "DiemTK_4": "3.24",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "CS102",
        "CurriculumName": "Tin học văn phòng",
        "CurriculumNamePrint": "Tin học văn phòng",
        "EnglishCurriculumName": "",
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "6.80",
        "DiemTK_4": "2.72",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "EC102",
        "CurriculumName": "Nhập môn kinh tế học",
        "CurriculumNamePrint": "Nhập môn kinh tế học",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "5.80",
        "DiemTK_4": "2.32",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "GE111",
        "CurriculumName": "Tiếng Anh sơ cấp 1",
        "CurriculumNamePrint": "Tiếng Anh sơ cấp 1",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "5.30",
        "DiemTK_4": "2.12",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "GE112",
        "CurriculumName": "Tiếng Anh sơ cấp 2",
        "CurriculumNamePrint": "Tiếng Anh sơ cấp 2",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "4.90",
        "DiemTK_4": "1.96",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "GE121",
        "CurriculumName": "Tiếng Anh sơ trung cấp 1",
        "CurriculumNamePrint": "Tiếng Anh sơ trung cấp 1",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "5.60",
        "DiemTK_4": "2.24",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "GE222",
        "CurriculumName": "Tiếng Anh sơ trung cấp 2",
        "CurriculumNamePrint": "Tiếng Anh sơ trung cấp 2",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "5.40",
        "DiemTK_4": "2.16",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "GJ141E",
        "CurriculumName": "Tiếng Nhật sơ cấp 1",
        "CurriculumNamePrint": "Tiếng Nhật sơ cấp 1",
        "EnglishCurriculumName": null,
        "Credits": "4",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "6.80",
        "DiemTK_4": "2.72",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "GJ142E",
        "CurriculumName": "Tiếng Nhật sơ cấp 2",
        "CurriculumNamePrint": "Tiếng Nhật sơ cấp 2",
        "EnglishCurriculumName": null,
        "Credits": "4",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "6.10",
        "DiemTK_4": "2.44",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "GJ143",
        "CurriculumName": "Tiếng Nhật sơ cấp 3",
        "CurriculumNamePrint": "Tiếng Nhật sơ cấp 3",
        "EnglishCurriculumName": null,
        "Credits": "4",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "4.90",
        "DiemTK_4": "1.96",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "GJ174",
        "CurriculumName": "Bổ trợ kỹ năng tiếng Nhật sơ cấp",
        "CurriculumNamePrint": "Bổ trợ kỹ năng tiếng Nhật sơ cấp",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "6.90",
        "DiemTK_4": "2.76",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "GJ240",
        "CurriculumName": "Tiếng Nhật trung cấp 1",
        "CurriculumNamePrint": "Tiếng Nhật trung cấp 1",
        "EnglishCurriculumName": null,
        "Credits": "4",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "6.00",
        "DiemTK_4": "2.40",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "GJ242",
        "CurriculumName": "Tiếng Nhật trung cấp 2",
        "CurriculumNamePrint": "Tiếng Nhật trung cấp 2",
        "EnglishCurriculumName": null,
        "Credits": "4",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "5.40",
        "DiemTK_4": "2.16",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "GJ243",
        "CurriculumName": "Tiếng Nhật trung cấp 3",
        "CurriculumNamePrint": "Tiếng Nhật trung cấp 3",
        "EnglishCurriculumName": null,
        "Credits": "4",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "5.50",
        "DiemTK_4": "2.20",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "GJ270",
        "CurriculumName": "Bổ trợ kỹ năng tiếng Nhật trung cấp 1",
        "CurriculumNamePrint": "Bổ trợ kỹ năng tiếng Nhật trung cấp 1",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "7.30",
        "DiemTK_4": "2.92",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "GJ272",
        "CurriculumName": "Bổ trợ kỹ năng tiếng Nhật trung cấp 2",
        "CurriculumNamePrint": "Bổ trợ kỹ năng tiếng Nhật trung cấp 2",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "7.60",
        "DiemTK_4": "3.04",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "GJ273",
        "CurriculumName": "Bổ trợ kỹ năng tiếng Nhật trung cấp 3",
        "CurriculumNamePrint": "Bổ trợ kỹ năng tiếng Nhật trung cấp 3",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "7.60",
        "DiemTK_4": "3.04",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "GJ343",
        "CurriculumName": "Tiếng Nhật cao cấp 1",
        "CurriculumNamePrint": "Tiếng Nhật cao cấp 1",
        "EnglishCurriculumName": null,
        "Credits": "4",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "6.20",
        "DiemTK_4": "2.48",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "GJ371",
        "CurriculumName": "Bổ trợ kỹ năng tiếng Nhật cao cấp 1",
        "CurriculumNamePrint": "Bổ trợ kỹ năng tiếng Nhật cao cấp 1",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "9.20",
        "DiemTK_4": "3.68",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "GZ101",
        "CurriculumName": "Tiếng Trung 1",
        "CurriculumNamePrint": "Tiếng Trung 1",
        "EnglishCurriculumName": "",
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "8.80",
        "DiemTK_4": "3.52",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": "Ngoài chương trình",
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "IS203",
        "CurriculumName": "Vi tính tiếng Nhật",
        "CurriculumNamePrint": "Vi tính tiếng Nhật",
        "EnglishCurriculumName": null,
        "Credits": "3",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "7.50",
        "DiemTK_4": "3.00",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "MA100",
        "CurriculumName": "Logic và suy luận toán học",
        "CurriculumNamePrint": "Logic và suy luận toán học",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "4.50",
        "DiemTK_4": "1.80",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "ML113",
        "CurriculumName": "Triết học Mác - Lênin",
        "CurriculumNamePrint": "Triết học Mác - Lênin",
        "EnglishCurriculumName": "",
        "Credits": "3",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "7.20",
        "DiemTK_4": "2.88",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "ML114",
        "CurriculumName": "Kinh tế chính trị Mác - Lênin",
        "CurriculumNamePrint": "Kinh tế chính trị Mác - Lênin",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "7.00",
        "DiemTK_4": "2.80",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "ML115",
        "CurriculumName": "Chủ nghĩa xã hội khoa học",
        "CurriculumNamePrint": "Chủ nghĩa xã hội khoa học",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "8.80",
        "DiemTK_4": "3.52",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "ML202",
        "CurriculumName": "Tư tưởng Hồ Chí Minh",
        "CurriculumNamePrint": "Tư tưởng Hồ Chí Minh",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "7.80",
        "DiemTK_4": "3.12",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "ML204",
        "CurriculumName": "Lịch sử Đảng Cộng sản Việt Nam",
        "CurriculumNamePrint": "Lịch sử Đảng Cộng sản Việt Nam",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "8.20",
        "DiemTK_4": "3.28",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "NA151",
        "CurriculumName": "Khoa học môi trường",
        "CurriculumNamePrint": "Khoa học môi trường",
        "EnglishCurriculumName": "",
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "7.10",
        "DiemTK_4": "2.84",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "PG102",
        "CurriculumName": "GDTC: Thể dục cổ truyền cơ bản <span style=\"color:red\">*</span>",
        "CurriculumNamePrint": "GDTC: Thể dục cổ truyền cơ bản *",
        "EnglishCurriculumName": "",
        "Credits": "1",
        "CurriculumGroupID": "PC",
        "DiemTK_10": "6.30",
        "DiemTK_4": "2.52",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": true,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": true,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "PG118",
        "CurriculumName": "GDTC: Thể dục cơ bản <span style=\"color:red\">*</span>",
        "CurriculumNamePrint": "GDTC: Thể dục cơ bản *",
        "EnglishCurriculumName": "",
        "Credits": "1",
        "CurriculumGroupID": "PC",
        "DiemTK_10": "6.60",
        "DiemTK_4": "2.64",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": true,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "PG121",
        "CurriculumName": "Giáo dục quốc phòng <span style=\"color:red\">*</span>",
        "CurriculumNamePrint": "Giáo dục quốc phòng *",
        "EnglishCurriculumName": null,
        "Credits": "4",
        "CurriculumGroupID": "DC",
        "DiemTK_10": "5.90",
        "DiemTK_4": "2.36",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": true,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "SH131",
        "CurriculumName": "Pháp luật đại cương",
        "CurriculumNamePrint": "Pháp luật đại cương",
        "EnglishCurriculumName": "",
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "7.50",
        "DiemTK_4": "3.00",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "VC200",
        "CurriculumName": "Văn hoá Việt Nam",
        "CurriculumNamePrint": "Văn hoá Việt Nam",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "9.00",
        "DiemTK_4": "3.60",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "VL100",
        "CurriculumName": "Ngôn ngữ học đại cương",
        "CurriculumNamePrint": "Ngôn ngữ học đại cương",
        "EnglishCurriculumName": "",
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "7.40",
        "DiemTK_4": "2.96",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    },
    {
        "StudentID": "A44369",
        "StudentName": "CHU THỊ THANH HUYỀN",
        "StudentName_Eng": "",
        "BirthDay": "07/05/2003",
        "GenderVN": "Nữ",
        "BirthPlace": "",
        "BirthPlace_Eng": "",
        "MobilePhone": "0364052864",
        "ClassStudentID": "NJ35CL01",
        "ClassStudentName": "NJ35CL01",
        "EnglishClassStudentName": "NJ35CL01",
        "GraduateLevelID": "DH",
        "GraduateLevelName": "Đại học",
        "EnglishGraduateLevelName": "Bachelor (BA)",
        "StudyTypeName": "Chính quy",
        "OlogyID": "NJ",
        "OlogyName": "NGÔN NGỮ NHẬT",
        "OlogyEngName": "NGÔN NGỮ NHẬT",
        "ScheduleStudyUnitID": null,
        "StudyProgramID": "DHCQK35NJ",
        "YearStudy": "",
        "TermID": "",
        "StudyUnitID": "",
        "CurriculumID": "VL101",
        "CurriculumName": "Tiếng Việt thực hành",
        "CurriculumNamePrint": "Tiếng Việt thực hành",
        "EnglishCurriculumName": null,
        "Credits": "2",
        "CurriculumGroupID": "NC",
        "DiemTK_10": "8.20",
        "DiemTK_4": "3.28",
        "DiemTK_Chu": null,
        "DiemChuyenMien": "M",
        "IsPass": "1",
        "IsGather": "x",
        "ToanKhoa": "1",
        "NamHoc": "1",
        "HocKy": "1",
        "NotScore": "0",
        "Note": null,
        "NotComputeAverageScore": false,
        "Dat_HK": "0",
        "TB_HK": "0.00",
        "Dat_TL_HK": "84",
        "TongTC_DK_HK": "84",
        "TB_TL_HK": "0.00",
        "DiemRenLuyenHK": null,
        "CourseTime": "2022 - 2026",
        "ThoiGianDaoTao": "4",
        "ChuyenNganh": "Bộ môn Ngôn ngữ Nhật",
        "AttendedDate": "Jul 30 2024 12:00AM",
        "T_TC_TL_TN": "84",
        "TB_TL_TN": "0.00",
        "TenXepLoai": null,
        "Eng_TenXepLoai": null,
        "SoHieuBang": null,
        "SoVaoSo": null,
        "QuyetDinhTotNghiep": "...",
        "NgayKyQuyetDinh": "...",
        "NgonNguDaoTao": null,
        "NotPrint": false,
        "KTESurvey": 0,
        "DGKS": 1,
        "SurveyClassID": "",
        "SurveyData": "",
        "ListOfProfessorID": "",
        "ListOfProfessorName": "",
        "_TermID": 3,
        "MD5": "482538acd1e2d9be5a750e95d31a6dc5"
    }
]
export default function Summary() {
    const [scores, setScores] = useState([]);
    const [total, setTotal] = useState(1);
    const [average, setAverage] = useState(0);
    const [totalGPA, setTotalGPA] = useState(0);
    useEffect(() => {
        (async () => {
            const filterArray = masterData.map(item => {
                return {
                    "CurriculumName": item.CurriculumName,
                    "Credits": item.Credits,
                    "DiemTK_10": item.DiemTK_10,
                    "IsPass": item.IsPass,
                    "NotComputeAverageScore": item.NotComputeAverageScore,
                    "TongTC_DK_HK": item.TongTC_DK_HK,
                    "DiemTK_4": item.DiemTK_4
                }
            })
            setScores(filterArray);
            // Calculate average score
            const totalScore = filterArray.reduce((acc, curr) => {
                if (!curr.NotComputeAverageScore) {
                    return acc + (parseFloat(curr.DiemTK_10) * parseFloat(curr.Credits));
                }
                return acc;
            }, 0);

            // Calculate GPA (4.0 scale)
            const totalGPA = filterArray.reduce((acc, curr) => {
                if (!curr.NotComputeAverageScore) {
                    return acc + (parseFloat(curr.DiemTK_4) * parseFloat(curr.Credits));
                }
                return acc;
            }, 0);

            const totalCredits = filterArray.reduce((acc, curr) => {
                if (!curr.NotComputeAverageScore) {
                    return acc + parseFloat(curr.Credits);
                }
                return acc;
            }, 0);
            setTotal(totalCredits);
            setAverage(totalScore / totalCredits);
            setTotalGPA(totalGPA / totalCredits);
        })()
    }, [])

    return (
        <div className="p-4 max-w-4xl mx-auto">
            <div className="mb-4">
                <p>Tổng số tín chỉ: {total}</p>
                <p>Điểm tổng kết (hệ 10): {average.toFixed(2)}</p>
                <p>Điểm GPA (hệ 4): {totalGPA.toFixed(2)}</p>
            </div>
            
            <table className="w-full border-collapse border">
                <thead>
                    <tr className="bg-gray-100">
                        <th className="border p-2">Tên môn học</th>
                        <th className="border p-2">Số tín chỉ</th>
                        <th className="border p-2">Điểm hệ 10</th>
                        <th className="border p-2">Điểm hệ 4</th>
                    </tr>
                </thead>
                <tbody>
                    {scores.map((score, index) => (
                        <tr key={index}>
                            <td className="border p-2" dangerouslySetInnerHTML={{__html: score.CurriculumName}} />
                            <td className="border p-2 text-center">{score.Credits}</td>
                            <td className="border p-2 text-center">{score.DiemTK_10}</td>
                            <td className="border p-2 text-center">{score.DiemTK_4}</td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    )
}
